project = logipi
vendor = xilinx
family = spartan6
part = xc6slx9-3-tqg144
top_module = top_level

#vfiles = ../verilog/xessdemo.v 
vhdlfiles = top_level.vhd  \
	SDRAM_Controller.vhd \
	Memory_tester.vhd \
	sdram_model.vhd \
	blinker.vhd \
	capture.vhd \
	transmitter.vhd \
	cheapscope.vhd

include ../common/xilinx.mk
