project = mz700
vendor = xilinx
family = spartan6
part = xc6slx9-3-tqg144
top_module = mz700

#vfiles = ../verilog/xessdemo.v 
vhdlfiles = cgrom.vhd \
			counter0.vhd \
			counter1.vhd \
counter2.vhd \
dpram2k.vhd \
exrom.vhd \
i8253.vhd \
i8255.vhd \
keymatrix.vhd \
ls367.vhd \
memsel.vhd \
mrom.vhd \
my_dcm1.vhd \
my_dcm2.vhd \
mz700.vhd \
ps2kb.vhd \
psio.vhd \
T80.vhd \
T80_ALU.vhd \
T80_MCode.vhd \
T80_Pack.vhd \
T80_Reg.vhd \
T80s.vhd \
vgaout.vhd \
kcpsm6.vhd \
sram.vhd \
prom.vhd


include ../common/xilinx.mk
