project = spi_flash
vendor = xilinx
family = spartan6
part = xc6slx9-3-tqg144
top_module = spi_N25Q128_programmer

vfiles =  
vhdlfiles = N25Q128_uart_programmer.vhd \
	spi_prog.vhd \
	uart_rx6.vhd \
	uart_tx6.vhd \
	kcpsm6.vhd 

include ../common/xilinx.mk
